### ISSUE TITLE
cannot import workflows when this is on.

### ISSUE THREAD

**Issue by klinter007** [niknah/quick-connections#6]
as title says

**Comment by niknah** [comment]
I can import ok.  Any errors?  Do you have the workflow that's not importing?
Maybe press F12, go to console and then import to see what's going on.

**Comment by zymox** [comment]
I have the same problem. Dragging an image/workflow into the screen or loading via menu just seems to be ignored. 
No output in console, neither in the command line nor browser/F12.

I have completely uninstalled quick-connections and it still doesn't work. After installing quick-connections I also updated all of Comfy, maybe this is caused by another extension.

**Comment by niknah** [comment]
I think this is fixed in https://github.com/niknah/quick-connections/issues/11
Send me a workflow if you have problems.
